parameters:
  - name: dotNetVersion
    type: string
    default: '9.x'
  - name: solutionFolder
    type: string
  - name: solutionPattern
    type: string
    default: '**/*.sln'
  - name: buildConfiguration
    type: string
    values:
      - Debug
      - Release
  - name: artifactName
    type: string
    default: 'app'

steps:
# Set .NET version
- task: UseDotNet@2
  displayName: Set .NET ${{ parameters.dotNetVersion }}
  inputs:
    version: ${{ parameters.dotNetVersion }}

# Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    workingDirectory: ${{ parameters.solutionFolder }}
    command: restore
    projects: ${{ parameters.solutionPattern }}
    arguments: >-
      --configuration ${{ parameters.buildConfiguration }}
      --no-restore

# Build the application
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    workingDirectory: ${{ parameters.solutionFolder }}
    command: build
    projects: ${{ parameters.solutionPattern }}
    arguments: >-
      --configuration ${{ parameters.buildConfiguration }}
      --no-restore

# Create artifact
- task: DotNetCoreCLI@2
  displayName: Create Artifact
  inputs:
    workingDirectory: ${{ parameters.solutionFolder }}
    command: publish
    projects: ${{ parameters.solutionPattern }}
    arguments: >-
      --configuration ${{ parameters.buildConfiguration }}
      --no-restore
      --output $(Build.ArtifactStagingDirectory)

# Publish the application
- task: PublishPipelineArtifact@1
  displayName: Publish Artifact
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifactName: ${{ parameters.artifactName }}
    publishLocation: pipeline
