parameters:
  - name: dotNetVersion
    type: string
    default: '9.x'
  - name: solutionFolder
    type: string
  - name: solutionPattern
    type: string
    default: '**/*.sln'

jobs:
  - job: Test
    displayName: Test Application
    steps:
      - template: ../steps/test.yml
        parameters:
          dotNetVersion: ${{ parameters.dotNetVersion }}
          solutionFolder: ${{ parameters.solutionFolder }}
          solutionPattern: ${{ parameters.solutionPattern }}
