trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: booleanParam
    type: boolean
    default: true
  - name: stringParam
    type: string
    default: 'option1'
    values:
      - 'option1'
      - 'option2'
      - 'option3'
  - name: numberParam
    type: number
    default: 42

steps:
- bash: |
    echo "Boolean Parameter: ${{ parameters.booleanParam }}"
    echo "String Parameter: ${{ parameters.stringParam }}"
    echo "Number Parameter: ${{ parameters.numberParam }}"
  displayName: 'Display Parameters'

- bash: |
    echo "This step runs only if the boolean parameter is true."
  displayName: Run if boolean parameter is true
  condition: ${{ eq(parameters.booleanParam, true) }}

- ${{ if eq(parameters.booleanParam, true) }}:
    - bash: |
        echo "This step shows only if the boolean parameter is true."
      displayName: Show if boolean parameter is true

- bash: |
    echo "More template expressions can be found in the documentation: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/template-expressions?view=azure-devops"
  displayName: 'More Template Expressions'