trigger:
- main

pool:
  vmImage: windows-latest # ubuntu 2404 has issues with .NET

variables:
  - name: solutionFolder
    value: $(Build.SourcesDirectory)/src
  - name: solutionPattern
    value: '**/*.sln' # Usually only Patterns must be in quotes
  - name: artifactName
    value: app

steps:
- task: UseDotNet@2
  displayName: Set .NET Version
  inputs:
    version: '9.x'

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    workingDirectory: $(solutionFolder)
    command: restore
    projects: $(solutionPattern)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    workingDirectory: $(solutionFolder)
    command: build
    projects: $(solutionPattern)
    arguments: >-
     --configuration Release
     --no-restore

- task: DotNetCoreCLI@2
  displayName: Create Artifact
  inputs:
    workingDirectory: $(solutionFolder)
    command: publish
    projects: $(solutionPattern)
    arguments: >-
     --configuration Release
     --no-restore
     --output $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@1
  displayName: Publish Artifact
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifactName: $(artifactName)
    publishLocation: pipeline
