trigger:
- main

pool:
  vmImage: windows-latest # ubuntu 2404 has issues with .NET

variables:
  - name: solutionFolder
    value: $(Build.SourcesDirectory)/src
  - name: solutionPattern
    value: '**/*.sln' # Usually only Patterns must be in quotes
  - name: artifactName
    value: app
  - name: azureSubscription
    value: training-service-connection
  - name: azureWebAppName
    value: 101r

stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: ./jobs/build.yml
        parameters:
          dotNetVersion: '9.x'
          solutionFolder: $(solutionFolder)
          solutionPattern: $(solutionPattern)
          buildConfiguration: Release
          artifactName: $(artifactName)

      - template: ./jobs/test.yml
        parameters:
          solutionFolder: $(solutionFolder)
          solutionPattern: $(solutionPattern)
      
  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    jobs:
      - template: ./jobs/deploy.yml
        parameters:
          azureSubscription: $(azureSubscription)
          azureWebAppName: $(azureWebAppName)
          artifactName: $(artifactName)
